/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.GUI;


/**
 *
 * @author nguye
 */
public class Xulivipham extends javax.swing.JPanel {

   
    public Xulivipham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Thembtn = new javax.swing.JButton();
        Capnhatbtn1 = new javax.swing.JButton();
        Xoabtn1 = new javax.swing.JButton();

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã xử lí", "Mã thành viên", "Hình thức xử lí", "Số tiền", "Ngày xử lí", "Trạng thái xử lí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Thembtn.setBackground(new java.awt.Color(153, 153, 153));
        Thembtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        Thembtn.setIcon(new javax.swing.ImageIcon("D:\\HocKi2\\Java\\image\\image\\add_36px.png")); // NOI18N
        Thembtn.setText("THÊM");

        Capnhatbtn1.setBackground(new java.awt.Color(153, 153, 153));
        Capnhatbtn1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        Capnhatbtn1.setIcon(new javax.swing.ImageIcon("D:\\HocKi2\\Java\\image\\image\\edit_36px.png")); // NOI18N
        Capnhatbtn1.setText("CẬP NHẬT");

        Xoabtn1.setBackground(new java.awt.Color(153, 153, 153));
        Xoabtn1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        Xoabtn1.setIcon(new javax.swing.ImageIcon("D:\\HocKi2\\Java\\image\\image\\delete_36px.png")); // NOI18N
        Xoabtn1.setText("XÓA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Thembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(Capnhatbtn1)
                .addGap(91, 91, 91)
                .addComponent(Xoabtn1)
                .addContainerGap(186, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thembtn)
                    .addComponent(Capnhatbtn1)
                    .addComponent(Xoabtn1))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Capnhatbtn1;
    private javax.swing.JButton Thembtn;
    private javax.swing.JButton Xoabtn1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
